name: latihan_flutter_rafly
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2
  get: ^4.6.5
  http: ^1.1.0
  intl: ^0.18.1
  connectivity: ^3.0.6
  connectivity_plus: ^4.0.2
  image_picker: ^1.0.4
  cupertino_icons: ^1.0.6
  camera: ^0.10.5+4
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^10.4.5
  file_picker: ^5.5.0
  timezone: ^0.9.2
  rxdart: ^0.27.7
#  flutter_native_timezone: ^2.0.0
  firebase_core: ^2.15.1
  flutter_local_notifications: ^15.1.1
  firebase_messaging: ^14.6.7
  logger: ^2.0.2
  cloud_firestore: ^4.9.1
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/e-collector.png"

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
